# Generated by Django 2.2.15 on 2020-08-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200817_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='years',
            name='yearDate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
