# Generated by Django 2.2.15 on 2020-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200820_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
