# Generated by Django 2.2.15 on 2020-08-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_discussion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-rating']},
        ),
    ]
