# Generated by Django 2.2.15 on 2020-09-21 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0009_auto_20200823_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('spoiler', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbID', models.IntegerField(unique=True)),
                ('poster', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('rating', models.FloatField(null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('actors', models.ManyToManyField(blank=True, to='movies.Actor')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genres')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Languages')),
                ('years', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Years')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.RemoveField(
            model_name='movies',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='years',
        ),
        migrations.AlterField(
            model_name='list',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.AddField(
            model_name='comment',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
